version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/cci-demo-docker-primary:0.0.2
      - image: postgres:9.4.1

   

    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1
     
      - run:
          name: Install Docker client
         
     
      - run:
          name: Install Docker Compose
      

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
          
      